import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
// import { gql, useLazyQuery, useQuery } from "@apollo/client";
import { ChangeEvent, HtmlHTMLAttributes, useState } from 'react';

// const GET_ALL_USERS = gql`
//   query {
//     getAllUsers {
//       id, username
//     }
//   }
// `

// const GET_USER = gql`
//   query Dog($id: id) {
//     getUser(id: $id) {
//       id,username
//     }
//   }
// `;

const Home: NextPage = () => {
  const [userId, setUserId] = useState<any>();
  // const { data, error } = useQuery(GET_ALL_USERS);
  // const [getUser, { loading, error, data }] = useLazyQuery(GET_USER);


  // const searchUser = () => {
  //   console.log(data);
  //   getUser({ variables: { ID: userId } })
  // }

  const change = (e: ChangeEvent<HTMLInputElement>) => {
    console.log(e.target.value);
    setUserId(e.target.value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Input UserName</h1>
      <input type="text" value={userId} onChange={(e) => change(e)} />
      {userId}
      {/* <button onClick={searchUser}>search user id</button> */}
    </div>
  )
}

export default Home
