import { NextPage } from "next";
import AuthLayout from "component/layout/AuthLayout";
import styles from "styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      {/*<Head>*/}
      {/*  <title>Create Next App</title>*/}
      {/*  <meta name="222" content="Generated by create next app" />*/}
      {/*  <link rel="icon" href="/favicon.ico" />*/}
      {/*</Head>*/}
      <main className={styles.main}>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores
        cupiditate ex magnam neque nostrum praesentium rerum tempore velit
        veniam voluptatem. Accusantium dolores in iusto maiores natus, nostrum
        nulla odit quae?
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: NextPage) {
  return <AuthLayout>{page}</AuthLayout>;
};

export default Home;
